import type { Metadata } from "next";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "./layout.module.css";
import "./globals.css";
import { CommonServerProps } from "@/types/CommonProps";
import { hasLocale } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from 'next-intl';
import { getTranslations } from 'next-intl/server';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<CommonServerProps>) {
  const { locale  } = await params ?? {};

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const t = await getTranslations('Footer');

  return (
    <html lang={locale as string}>
      <body className={`${geistSans.variable} ${geistMono.variable} ${styles.layout}`}>
        <header className={styles.layout__header}>
          <Image
            src="/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />
        </header>
        <main className={styles.layout__main}>
          <NextIntlClientProvider>
            {children}
          </NextIntlClientProvider>
        </main>
        <footer className={styles.layout__footer}>
          <p>{t("author", { name: "Aarón Velasco López" })}</p>
        </footer>
      </body>
    </html>
  );
}
