import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import { notFound } from "next/navigation";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { getMessages, getTranslations } from "next-intl/server";

import { routing } from "@/i18n/routing";
import { CommonServerLayout } from "@/types/CommonProps";

import styles from "./layout.module.css";
import "./globals.css";

import { LanguageNav } from "@/ui/components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: CommonServerLayout) {
  const { locale } = (await params) ?? {};

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = await getMessages();

  const t = await getTranslations("Footer");

  return (
    <html lang={locale as string}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${styles.layout}`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <header className={styles.layout__header}>
            <Image
              src="/next.svg"
              alt="Next.js logo"
              width={180}
              height={38}
              priority
            />
            <LanguageNav />
          </header>
          <main className={styles.layout__main}>{children}</main>
          <footer className={styles.layout__footer}>
            <p>{t("author", { name: "Aarón Velasco López" })}</p>
          </footer>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
